// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

//包名

package go_grpc_gateway_user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求参数
type Request struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

// 返回参数
type Response struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.grpc.gateway.user.Request")
	proto.RegisterType((*Response)(nil), "go.grpc.gateway.user.Response")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x49, 0xcf, 0xd7, 0x4b, 0x2f, 0x2a, 0x48, 0xd6,
	0x4b, 0x4f, 0x2c, 0x49, 0x2d, 0x4f, 0xac, 0xd4, 0x03, 0xc9, 0x49, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7,
	0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6,
	0xe7, 0x15, 0x43, 0xf4, 0x28, 0x49, 0x73, 0xb1, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0x09, 0x70, 0x31, 0x97, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x4a,
	0x72, 0x5c, 0x1c, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x79,
	0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x69, 0x30, 0xdb, 0xa8, 0x90, 0x8b, 0xdb, 0x3d, 0xb5, 0x24,
	0xb4, 0x38, 0xb5, 0xc8, 0x33, 0x2f, 0x2d, 0x5f, 0x28, 0x89, 0x8b, 0xdf, 0xbd, 0xa8, 0x20, 0x19,
	0x59, 0x48, 0x56, 0x0f, 0x9b, 0x9b, 0xf4, 0xa0, 0x56, 0x4a, 0xc9, 0xe1, 0x92, 0x86, 0x58, 0xaa,
	0x24, 0xd0, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x2e, 0x25, 0x56, 0x7d, 0x90, 0xb8, 0x15, 0xa3, 0x56,
	0x12, 0x1b, 0xd8, 0xd9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xfc, 0xab, 0x59, 0xf8,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetUserInfoClient is the client API for GetUserInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetUserInfoClient interface {
	GrpcGetUserInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getUserInfoClient struct {
	cc *grpc.ClientConn
}

func NewGetUserInfoClient(cc *grpc.ClientConn) GetUserInfoClient {
	return &getUserInfoClient{cc}
}

func (c *getUserInfoClient) GrpcGetUserInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.grpc.gateway.user.GetUserInfo/GrpcGetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserInfoServer is the server API for GetUserInfo service.
type GetUserInfoServer interface {
	GrpcGetUserInfo(context.Context, *Request) (*Response, error)
}

// UnimplementedGetUserInfoServer can be embedded to have forward compatible implementations.
type UnimplementedGetUserInfoServer struct {
}

func (*UnimplementedGetUserInfoServer) GrpcGetUserInfo(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrpcGetUserInfo not implemented")
}

func RegisterGetUserInfoServer(s *grpc.Server, srv GetUserInfoServer) {
	s.RegisterService(&_GetUserInfo_serviceDesc, srv)
}

func _GetUserInfo_GrpcGetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserInfoServer).GrpcGetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.grpc.gateway.user.GetUserInfo/GrpcGetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserInfoServer).GrpcGetUserInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetUserInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.grpc.gateway.user.GetUserInfo",
	HandlerType: (*GetUserInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrpcGetUserInfo",
			Handler:    _GetUserInfo_GrpcGetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
